env:
  TEST_DATABASE_NAME: Employee_test
  TEST_PORT: 3306
  TEST_USERNAME: root
  TEST_PASSWORD: 121212
  TEST_HOST: 127.0.0.1
name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services: 
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 121212
        ports:
          - 3306
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0 

      - name: start mysql client  
        run: sudo service mysql start 
      - name: Run bundle install
        run: |
            gem install bundler
            bundle install
      - name: create database    
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
      - name: Run rspec
        run: rspec .     